import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Unknown Today',
    description: 'Generated by create next app',
}

export default function RootLayout({children}: { children: React.ReactNode }) {
    return (
        <html lang="ja">
        <body className={inter.className}>
        <div className="container mx-auto">
            <header className="py-2">
                <h1>
                    <a href="/" className="block px-4"><img className="w-full aspect-[3237/1176]" src="/logo.svg" alt="Unknown Today"/></a>
                </h1>
            </header>
            <section className="w-full text-center py-3 border-y">
                <p className="inline">
                    この世界のニュースでは<strong className="font-bold">ありません</strong>
                </p>
                <a href="/about" className="ml-2">詳細</a>
            </section>
            {children}
        </div>
        </body>
        </html>
    )
}
